columns:  # which all colms we expect in data pulled frm mongo db
  - id: int
  - Gender: category
  - Age: int
  - Driving_License: int
  - Region_Code: float
  - Previously_Insured: int
  - Vehicle_Age: category
  - Vehicle_Damage: category
  - Annual_Premium: float
  - Policy_Sales_Channel: float
  - Vintage: int
  - Response: int


numerical_columns:  # are these oclms in data
  - Age
  - Driving_License
  - Region_Code
  - Previously_Insured
  - Annual_Premium
  - Policy_Sales_Channel
  - Vintage
  - Response

categorical_columns:
  - Gender
  - Vehicle_Age
  - Vehicle_Damage

drop_columns: _id   # drop colm will be taken frm here

# for data transformation
num_features:
  - Age
  - Vintage


mm_columns:  # min -max scaling colm
  - Annual_Premium